### ISSUE TITLE
Cannot import modules from external chp files

### ISSUE THREAD

**Issue by zauberparacelsus** [MyWorldLLC/Chipmunk#38]
Chipmunk is currently unable to import modules from outside the current .chp source file.

**Comment by danielperano** [comment]
This is a known limitation of the CLI - it currently has no mechanism for specifying or discovering code outside of the script it's running or built-in modules.

A search path and flags to address this will be added in an upcoming release.

**Comment by danielperano** [comment]
Fixed by b32e10894d2dc53ff12fbf9756cebc5660b374b0.
